package PopUpFrames;
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author nohea
 */
public class DissertationFrame extends javax.swing.JFrame {

    /**
     * Creates new form EditRemoveDissertation
     */
    public DissertationFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        DissertationRootPanel = new javax.swing.JPanel();
        editRemoveDissertationLabel = new javax.swing.JLabel();
        editRemoveDissertationPanel = new javax.swing.JPanel();
        eRDissertationTitleLabel = new javax.swing.JLabel();
        eRDissertationTitleTxt = new javax.swing.JTextField();
        eRDissertationPubYearLabel = new javax.swing.JLabel();
        eRDissertationPubYearTxt = new javax.swing.JTextField();
        eRDissertationDepLabel = new javax.swing.JLabel();
        eRDissertationDepTxt = new javax.swing.JTextField();
        eRDissertationDepBuildingLabel = new javax.swing.JLabel();
        eRDissertationDepBuildingTxt = new javax.swing.JTextField();
        eRDissertationChapLabel = new javax.swing.JLabel();
        eRDissertationChapTxt = new javax.swing.JTextField();
        eRDissertationFigLabel = new javax.swing.JLabel();
        eRDissertationFigTxt = new javax.swing.JTextField();
        eRDissertationAuthorLabel = new javax.swing.JLabel();
        eRDissertationAuthorTxt = new javax.swing.JTextField();
        eRDissertationComMemInstrucLabel = new javax.swing.JLabel();
        eRDissertationComMemLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        eRDissertationComMemTxt = new javax.swing.JTextArea();
        editDissertationBtn = new javax.swing.JButton();
        removeDissertationBtn = new javax.swing.JButton();
        addDissertationBtn = new javax.swing.JButton();
        backBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        DissertationRootPanel.setBackground(new java.awt.Color(60, 91, 118));

        editRemoveDissertationLabel.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 24)); // NOI18N
        editRemoveDissertationLabel.setForeground(new java.awt.Color(250, 250, 250));
        editRemoveDissertationLabel.setText("Add/Edit/Remove Dissertation");

        eRDissertationTitleLabel.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 14)); // NOI18N
        eRDissertationTitleLabel.setText("Title:");

        eRDissertationTitleTxt.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 14)); // NOI18N
        eRDissertationTitleTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eRDissertationTitleTxtActionPerformed(evt);
            }
        });

        eRDissertationPubYearLabel.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 14)); // NOI18N
        eRDissertationPubYearLabel.setText("Publication Year:");

        eRDissertationPubYearTxt.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 14)); // NOI18N

        eRDissertationDepLabel.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 14)); // NOI18N
        eRDissertationDepLabel.setText("Department:");

        eRDissertationDepTxt.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 14)); // NOI18N

        eRDissertationDepBuildingLabel.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 14)); // NOI18N
        eRDissertationDepBuildingLabel.setText("Building:");

        eRDissertationDepBuildingTxt.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 14)); // NOI18N

        eRDissertationChapLabel.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 14)); // NOI18N
        eRDissertationChapLabel.setText("Chapters:");

        eRDissertationChapTxt.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 14)); // NOI18N

        eRDissertationFigLabel.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 14)); // NOI18N
        eRDissertationFigLabel.setText("Number of Figures:");

        eRDissertationFigTxt.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 14)); // NOI18N

        eRDissertationAuthorLabel.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 14)); // NOI18N
        eRDissertationAuthorLabel.setText("Author:");

        eRDissertationAuthorTxt.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 14)); // NOI18N

        eRDissertationComMemInstrucLabel.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 14)); // NOI18N
        eRDissertationComMemInstrucLabel.setText("Enter the committee members, and committee name, and seprate them by a semicolon. (;)");

        eRDissertationComMemLabel.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 14)); // NOI18N
        eRDissertationComMemLabel.setText("Committee Members:");

        eRDissertationComMemTxt.setColumns(20);
        eRDissertationComMemTxt.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 14)); // NOI18N
        eRDissertationComMemTxt.setRows(5);
        jScrollPane1.setViewportView(eRDissertationComMemTxt);

        editDissertationBtn.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 18)); // NOI18N
        editDissertationBtn.setText("Edit Dissertation");

        removeDissertationBtn.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 18)); // NOI18N
        removeDissertationBtn.setText("Remove Dissertation");

        addDissertationBtn.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 18)); // NOI18N
        addDissertationBtn.setText("Add Dissertation");

        javax.swing.GroupLayout editRemoveDissertationPanelLayout = new javax.swing.GroupLayout(editRemoveDissertationPanel);
        editRemoveDissertationPanel.setLayout(editRemoveDissertationPanelLayout);
        editRemoveDissertationPanelLayout.setHorizontalGroup(
            editRemoveDissertationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(editRemoveDissertationPanelLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(eRDissertationComMemLabel)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 434, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                .addComponent(removeDissertationBtn)
                .addGap(72, 72, 72))
            .addGroup(editRemoveDissertationPanelLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(editRemoveDissertationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(editRemoveDissertationPanelLayout.createSequentialGroup()
                        .addGroup(editRemoveDissertationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(eRDissertationAuthorLabel)
                            .addComponent(eRDissertationFigLabel)
                            .addComponent(eRDissertationDepLabel)
                            .addComponent(eRDissertationPubYearLabel)
                            .addComponent(eRDissertationTitleLabel)
                            .addComponent(eRDissertationChapLabel))
                        .addGap(18, 18, 18)
                        .addGroup(editRemoveDissertationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(eRDissertationTitleTxt)
                            .addComponent(eRDissertationPubYearTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(editRemoveDissertationPanelLayout.createSequentialGroup()
                                .addComponent(eRDissertationDepTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(27, 27, 27)
                                .addComponent(eRDissertationDepBuildingLabel)
                                .addGap(18, 18, 18)
                                .addComponent(eRDissertationDepBuildingTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 133, Short.MAX_VALUE))
                            .addComponent(eRDissertationFigTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 375, Short.MAX_VALUE)
                            .addComponent(eRDissertationChapTxt)
                            .addComponent(eRDissertationAuthorTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(114, 114, 114)
                        .addComponent(addDissertationBtn))
                    .addGroup(editRemoveDissertationPanelLayout.createSequentialGroup()
                        .addComponent(eRDissertationComMemInstrucLabel)
                        .addGap(31, 31, 31)
                        .addComponent(editDissertationBtn)))
                .addContainerGap(96, Short.MAX_VALUE))
        );
        editRemoveDissertationPanelLayout.setVerticalGroup(
            editRemoveDissertationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(editRemoveDissertationPanelLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(editRemoveDissertationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(eRDissertationTitleLabel)
                    .addComponent(eRDissertationTitleTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(editRemoveDissertationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(eRDissertationPubYearLabel)
                    .addComponent(eRDissertationPubYearTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(editRemoveDissertationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(eRDissertationDepLabel)
                    .addComponent(eRDissertationDepTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(eRDissertationDepBuildingLabel)
                    .addComponent(eRDissertationDepBuildingTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(editRemoveDissertationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(eRDissertationChapLabel)
                    .addComponent(eRDissertationChapTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(editRemoveDissertationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(eRDissertationFigLabel)
                    .addComponent(eRDissertationFigTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(editRemoveDissertationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(eRDissertationAuthorLabel)
                    .addComponent(eRDissertationAuthorTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(eRDissertationComMemInstrucLabel)
                .addGap(18, 18, 18)
                .addGroup(editRemoveDissertationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(eRDissertationComMemLabel)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(37, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, editRemoveDissertationPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(addDissertationBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(editDissertationBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(removeDissertationBtn)
                .addGap(121, 121, 121))
        );

        backBtn.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 18)); // NOI18N
        backBtn.setText("Back to Search");

        javax.swing.GroupLayout DissertationRootPanelLayout = new javax.swing.GroupLayout(DissertationRootPanel);
        DissertationRootPanel.setLayout(DissertationRootPanelLayout);
        DissertationRootPanelLayout.setHorizontalGroup(
            DissertationRootPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DissertationRootPanelLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(editRemoveDissertationLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(backBtn)
                .addGap(55, 55, 55))
            .addGroup(DissertationRootPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(editRemoveDissertationPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        DissertationRootPanelLayout.setVerticalGroup(
            DissertationRootPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DissertationRootPanelLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(DissertationRootPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(editRemoveDissertationLabel)
                    .addComponent(backBtn))
                .addGap(18, 18, 18)
                .addComponent(editRemoveDissertationPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(DissertationRootPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(DissertationRootPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void eRDissertationTitleTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eRDissertationTitleTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_eRDissertationTitleTxtActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DissertationFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DissertationFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DissertationFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DissertationFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DissertationFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel DissertationRootPanel;
    private javax.swing.JButton addDissertationBtn;
    private javax.swing.JButton backBtn;
    private javax.swing.JLabel eRDissertationAuthorLabel;
    private javax.swing.JTextField eRDissertationAuthorTxt;
    private javax.swing.JLabel eRDissertationChapLabel;
    private javax.swing.JTextField eRDissertationChapTxt;
    private javax.swing.JLabel eRDissertationComMemInstrucLabel;
    private javax.swing.JLabel eRDissertationComMemLabel;
    private javax.swing.JTextArea eRDissertationComMemTxt;
    private javax.swing.JLabel eRDissertationDepBuildingLabel;
    private javax.swing.JTextField eRDissertationDepBuildingTxt;
    private javax.swing.JLabel eRDissertationDepLabel;
    private javax.swing.JTextField eRDissertationDepTxt;
    private javax.swing.JLabel eRDissertationFigLabel;
    private javax.swing.JTextField eRDissertationFigTxt;
    private javax.swing.JLabel eRDissertationPubYearLabel;
    private javax.swing.JTextField eRDissertationPubYearTxt;
    private javax.swing.JLabel eRDissertationTitleLabel;
    private javax.swing.JTextField eRDissertationTitleTxt;
    private javax.swing.JButton editDissertationBtn;
    private javax.swing.JLabel editRemoveDissertationLabel;
    private javax.swing.JPanel editRemoveDissertationPanel;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton removeDissertationBtn;
    // End of variables declaration//GEN-END:variables
}
