/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package application;

/**
 *
 * @author nohea
 */
public class MainFrame extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public MainFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        serachTypeBtnGroup = new javax.swing.ButtonGroup();
        RootPanel = new javax.swing.JPanel();
        MainMenuTabs = new javax.swing.JTabbedPane();
        SearchPane = new javax.swing.JPanel();
        InnerBodyPanel = new javax.swing.JPanel();
        searchTitleLabel = new javax.swing.JLabel();
        searchTitleTxt = new javax.swing.JTextField();
        searchAuthorLabel = new javax.swing.JLabel();
        searchAuthorTxt = new javax.swing.JTextField();
        searchPubYearLabel = new javax.swing.JLabel();
        searchPubYearTxt = new javax.swing.JTextField();
        searchTypePanel = new javax.swing.JPanel();
        searchTypeBookBtn = new javax.swing.JRadioButton();
        searchTypeThesisBtn = new javax.swing.JRadioButton();
        searchTypeDissertationBtn = new javax.swing.JRadioButton();
        searchTypeConferenceBtn = new javax.swing.JRadioButton();
        searchTypeResearchBtn = new javax.swing.JRadioButton();
        searchTypeJournalBtn = new javax.swing.JRadioButton();
        searchTypeMagazineBtn = new javax.swing.JRadioButton();
        searchBtn = new javax.swing.JButton();
        searchScrollpane = new javax.swing.JScrollPane();
        searchResultList = new javax.swing.JList<>();
        ItmSearchDescLabel = new javax.swing.JLabel();
        ItmSearchLabel = new javax.swing.JLabel();
        addItemBtn = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        GenReportPane = new javax.swing.JPanel();
        genReportBtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        genReportTree = new javax.swing.JTree();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        RootPanel.setBackground(new java.awt.Color(32, 58, 78));

        MainMenuTabs.setBackground(new java.awt.Color(203, 211, 217));
        MainMenuTabs.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 24)); // NOI18N

        SearchPane.setBackground(new java.awt.Color(60, 91, 118));
        SearchPane.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 14)); // NOI18N

        searchTitleLabel.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 14)); // NOI18N
        searchTitleLabel.setText("Title:");

        searchTitleTxt.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 14)); // NOI18N

        searchAuthorLabel.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 14)); // NOI18N
        searchAuthorLabel.setText("Author:");

        searchAuthorTxt.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 14)); // NOI18N

        searchPubYearLabel.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 14)); // NOI18N
        searchPubYearLabel.setText("Publication Year:");

        searchPubYearTxt.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 14)); // NOI18N

        searchTypePanel.setBackground(new java.awt.Color(203, 211, 217));

        serachTypeBtnGroup.add(searchTypeBookBtn);
        searchTypeBookBtn.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 14)); // NOI18N
        searchTypeBookBtn.setText("Book");

        serachTypeBtnGroup.add(searchTypeThesisBtn);
        searchTypeThesisBtn.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 14)); // NOI18N
        searchTypeThesisBtn.setText("Thesis");

        serachTypeBtnGroup.add(searchTypeDissertationBtn);
        searchTypeDissertationBtn.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 14)); // NOI18N
        searchTypeDissertationBtn.setText("Dissertation");

        serachTypeBtnGroup.add(searchTypeConferenceBtn);
        searchTypeConferenceBtn.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 14)); // NOI18N
        searchTypeConferenceBtn.setText("Conference Paper");

        serachTypeBtnGroup.add(searchTypeResearchBtn);
        searchTypeResearchBtn.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 14)); // NOI18N
        searchTypeResearchBtn.setText("Research Report");

        serachTypeBtnGroup.add(searchTypeJournalBtn);
        searchTypeJournalBtn.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 14)); // NOI18N
        searchTypeJournalBtn.setText("Journal Paper");

        serachTypeBtnGroup.add(searchTypeMagazineBtn);
        searchTypeMagazineBtn.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 14)); // NOI18N
        searchTypeMagazineBtn.setText("Magazine");

        javax.swing.GroupLayout searchTypePanelLayout = new javax.swing.GroupLayout(searchTypePanel);
        searchTypePanel.setLayout(searchTypePanelLayout);
        searchTypePanelLayout.setHorizontalGroup(
            searchTypePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(searchTypePanelLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(searchTypeBookBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(searchTypeThesisBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(searchTypeDissertationBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(searchTypeConferenceBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(searchTypeResearchBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(searchTypeJournalBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(searchTypeMagazineBtn)
                .addContainerGap(78, Short.MAX_VALUE))
        );
        searchTypePanelLayout.setVerticalGroup(
            searchTypePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(searchTypePanelLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(searchTypePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(searchTypeBookBtn)
                    .addComponent(searchTypeThesisBtn)
                    .addComponent(searchTypeDissertationBtn)
                    .addComponent(searchTypeConferenceBtn)
                    .addComponent(searchTypeResearchBtn)
                    .addComponent(searchTypeJournalBtn)
                    .addComponent(searchTypeMagazineBtn))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        searchBtn.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 14)); // NOI18N
        searchBtn.setText("Search");

        searchResultList.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 14)); // NOI18N
        searchResultList.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        searchScrollpane.setViewportView(searchResultList);

        javax.swing.GroupLayout InnerBodyPanelLayout = new javax.swing.GroupLayout(InnerBodyPanel);
        InnerBodyPanel.setLayout(InnerBodyPanelLayout);
        InnerBodyPanelLayout.setHorizontalGroup(
            InnerBodyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(InnerBodyPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(InnerBodyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(InnerBodyPanelLayout.createSequentialGroup()
                        .addComponent(searchTypePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(InnerBodyPanelLayout.createSequentialGroup()
                        .addComponent(searchTitleLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(searchTitleTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(searchAuthorLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(searchAuthorTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(searchPubYearLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(searchPubYearTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(searchBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(25, 25, 25))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, InnerBodyPanelLayout.createSequentialGroup()
                        .addComponent(searchScrollpane)
                        .addContainerGap())))
        );
        InnerBodyPanelLayout.setVerticalGroup(
            InnerBodyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(InnerBodyPanelLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(InnerBodyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(searchTitleLabel)
                    .addComponent(searchTitleTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(searchAuthorLabel)
                    .addComponent(searchAuthorTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(searchPubYearLabel)
                    .addComponent(searchPubYearTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(searchBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(searchTypePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(searchScrollpane, javax.swing.GroupLayout.DEFAULT_SIZE, 284, Short.MAX_VALUE)
                .addContainerGap())
        );

        ItmSearchDescLabel.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 18)); // NOI18N
        ItmSearchDescLabel.setForeground(new java.awt.Color(250, 250, 250));
        ItmSearchDescLabel.setText("Item Search");
        ItmSearchDescLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        ItmSearchLabel.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 14)); // NOI18N
        ItmSearchLabel.setForeground(new java.awt.Color(250, 250, 250));
        ItmSearchLabel.setText("Please select the type of item you are looking for.");

        addItemBtn.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 14)); // NOI18N
        addItemBtn.setText("Add Item of Selected Type");

        jButton1.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 14)); // NOI18N
        jButton1.setText("Edit/Remove Selected Item");

        javax.swing.GroupLayout SearchPaneLayout = new javax.swing.GroupLayout(SearchPane);
        SearchPane.setLayout(SearchPaneLayout);
        SearchPaneLayout.setHorizontalGroup(
            SearchPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SearchPaneLayout.createSequentialGroup()
                .addGroup(SearchPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(SearchPaneLayout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addGroup(SearchPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(SearchPaneLayout.createSequentialGroup()
                                .addComponent(ItmSearchLabel)
                                .addGap(45, 45, 45)
                                .addComponent(addItemBtn)
                                .addGap(18, 18, 18)
                                .addComponent(jButton1))
                            .addComponent(ItmSearchDescLabel)))
                    .addGroup(SearchPaneLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(InnerBodyPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        SearchPaneLayout.setVerticalGroup(
            SearchPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SearchPaneLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(ItmSearchDescLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(SearchPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ItmSearchLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addItemBtn)
                    .addComponent(jButton1))
                .addGap(23, 23, 23)
                .addComponent(InnerBodyPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        MainMenuTabs.addTab("Search", SearchPane);

        GenReportPane.setBackground(new java.awt.Color(60, 91, 118));
        GenReportPane.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 24)); // NOI18N

        genReportBtn.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 18)); // NOI18N
        genReportBtn.setText("Generate Report");

        genReportTree.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 14)); // NOI18N
        jScrollPane1.setViewportView(genReportTree);

        javax.swing.GroupLayout GenReportPaneLayout = new javax.swing.GroupLayout(GenReportPane);
        GenReportPane.setLayout(GenReportPaneLayout);
        GenReportPaneLayout.setHorizontalGroup(
            GenReportPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(GenReportPaneLayout.createSequentialGroup()
                .addGroup(GenReportPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(GenReportPaneLayout.createSequentialGroup()
                        .addGap(337, 337, 337)
                        .addComponent(genReportBtn))
                    .addGroup(GenReportPaneLayout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 754, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(61, Short.MAX_VALUE))
        );
        GenReportPaneLayout.setVerticalGroup(
            GenReportPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(GenReportPaneLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(genReportBtn)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1)
                .addContainerGap())
        );

        MainMenuTabs.addTab("Generate Report", GenReportPane);

        javax.swing.GroupLayout RootPanelLayout = new javax.swing.GroupLayout(RootPanel);
        RootPanel.setLayout(RootPanelLayout);
        RootPanelLayout.setHorizontalGroup(
            RootPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MainMenuTabs)
        );
        RootPanelLayout.setVerticalGroup(
            RootPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MainMenuTabs)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(RootPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(RootPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel GenReportPane;
    private javax.swing.JPanel InnerBodyPanel;
    private javax.swing.JLabel ItmSearchDescLabel;
    private javax.swing.JLabel ItmSearchLabel;
    private javax.swing.JTabbedPane MainMenuTabs;
    private javax.swing.JPanel RootPanel;
    private javax.swing.JPanel SearchPane;
    private javax.swing.JButton addItemBtn;
    private javax.swing.JButton genReportBtn;
    private javax.swing.JTree genReportTree;
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel searchAuthorLabel;
    private javax.swing.JTextField searchAuthorTxt;
    private javax.swing.JButton searchBtn;
    private javax.swing.JLabel searchPubYearLabel;
    private javax.swing.JTextField searchPubYearTxt;
    private javax.swing.JList<String> searchResultList;
    private javax.swing.JScrollPane searchScrollpane;
    private javax.swing.JLabel searchTitleLabel;
    private javax.swing.JTextField searchTitleTxt;
    private javax.swing.JRadioButton searchTypeBookBtn;
    private javax.swing.JRadioButton searchTypeConferenceBtn;
    private javax.swing.JRadioButton searchTypeDissertationBtn;
    private javax.swing.JRadioButton searchTypeJournalBtn;
    private javax.swing.JRadioButton searchTypeMagazineBtn;
    private javax.swing.JPanel searchTypePanel;
    private javax.swing.JRadioButton searchTypeResearchBtn;
    private javax.swing.JRadioButton searchTypeThesisBtn;
    private javax.swing.ButtonGroup serachTypeBtnGroup;
    // End of variables declaration//GEN-END:variables
}
