/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.finalprojectgui;

import java.util.List;
import java.util.ArrayList;
import javax.swing.DefaultListModel;

/**
 *
 * @author Lani
 */
public class LMS extends javax.swing.JFrame {
    /*Things that need to be finished/addressed:
    The remove/edit/search tab
    
    1.  Figure out how the Jlist modeling works
    2.  The BookStrList SHOULD be what makes up the JList. I'm thinking it should 
        be built from calling the title and publisher variables from each book and 
        concatentating them together, then adding those into a string array.
    3.  This string array should be used in the JList, while the BookList array should be
        updates simultaneously
    4.  My idea was to have the edit button open up a tabbed panel wherein each panel
        correlates to a specific book type, however this is NOT working, so it will likely
        need to be replaced with something else
    
    Adding book tab
    1.  Again, need help figuring out Jlists. We're going to have alot of lists
        considering all the complex classes that are being made (I.E, Committee members,
        author lists)
    2.  Example of the above is going to be the author name adding list. I'm thinking
        the idea here is that it accepts first and last name together, then splits
        them so they can be added separately like they are defined in the classes
    3.  I have some example sections completed, but there's a lot left to do
    
    Generating report
    1.  This is almost done, just need book classes to be implemented, the code 
        SHOULD work.
    2.  The important thing the existing code uses that I'm pretty sure doesn't exist
        in the class files yet is the toString method. Once those are made for
        each and every class, then we'll be good.
    */
    
    //Updated list containing title + publisher, used in remove book and book editor
    private final List<String> BookStrList = new ArrayList<>();
    //private finale List<Publication> BookList = new ArrayList<>(); <--NOTE, NEEDS IMPLEMENTATION
    DefaultListModel model = new DefaultListModel();
    /**
     * Creates new form LMS
     */
    public LMS() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        RootPanel = new javax.swing.JPanel();
        MultiPaneLMS = new javax.swing.JTabbedPane();
        AddBookPane = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        AddBookPanel = new javax.swing.JPanel();
        AddThesisPanel = new javax.swing.JPanel();
        AddDissertationPanel = new javax.swing.JPanel();
        AddConferencePanel = new javax.swing.JPanel();
        AddJournalPanel = new javax.swing.JPanel();
        AddResearchPanel = new javax.swing.JPanel();
        AddResearchPalettePanel1 = new javax.swing.JPanel();
        AddResearchTitleLable = new javax.swing.JLabel();
        AddResearchPublisherLabel = new javax.swing.JLabel();
        AddMagazineTitleTxt1 = new javax.swing.JTextField();
        AddResearchPublisherTxt1 = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        AddResearchPaperAuthorLTxt = new javax.swing.JTextField();
        AddMagazinePanel = new javax.swing.JPanel();
        AddMagazinePalettePanel = new javax.swing.JPanel();
        AddMagazineTitleLable = new javax.swing.JLabel();
        AddMagazinePublisherLabel = new javax.swing.JLabel();
        AddMagazineTitleTxt = new javax.swing.JTextField();
        AddMagazinePublisherTxt = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        RemoveBookPane = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        BookJList = new javax.swing.JList<>();
        RemoveBookButton = new javax.swing.JButton();
        VerificationPanel = new javax.swing.JPanel();
        VerificationLabel = new javax.swing.JLabel();
        VerificationYesButton = new javax.swing.JButton();
        VerificationNoButton = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        EdittingPane = new javax.swing.JTabbedPane();
        EditBookResearchPaper = new javax.swing.JPanel();
        AddResearchTitleLable5 = new javax.swing.JLabel();
        AddResearchPublisherLabel5 = new javax.swing.JLabel();
        AddMagazineTitleTxt2 = new javax.swing.JTextField();
        AddResearchPublisherTxt6 = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane8 = new javax.swing.JScrollPane();
        jList6 = new javax.swing.JList<>();
        AddResearchPaperAuthorLTxt5 = new javax.swing.JTextField();
        EditBookMagazine = new javax.swing.JPanel();
        AddMagazineTitleLable1 = new javax.swing.JLabel();
        AddMagazinePublisherLabel1 = new javax.swing.JLabel();
        AddMagazineTitleTxt7 = new javax.swing.JTextField();
        AddMagazinePublisherTxt1 = new javax.swing.JTextField();
        jButton9 = new javax.swing.JButton();
        GenerateReportPane = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        ReportTextArea = new javax.swing.JTextArea();
        GenReportButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Library Management System");

        javax.swing.GroupLayout AddBookPanelLayout = new javax.swing.GroupLayout(AddBookPanel);
        AddBookPanel.setLayout(AddBookPanelLayout);
        AddBookPanelLayout.setHorizontalGroup(
            AddBookPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        AddBookPanelLayout.setVerticalGroup(
            AddBookPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Book", AddBookPanel);

        javax.swing.GroupLayout AddThesisPanelLayout = new javax.swing.GroupLayout(AddThesisPanel);
        AddThesisPanel.setLayout(AddThesisPanelLayout);
        AddThesisPanelLayout.setHorizontalGroup(
            AddThesisPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        AddThesisPanelLayout.setVerticalGroup(
            AddThesisPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Thesis", AddThesisPanel);

        javax.swing.GroupLayout AddDissertationPanelLayout = new javax.swing.GroupLayout(AddDissertationPanel);
        AddDissertationPanel.setLayout(AddDissertationPanelLayout);
        AddDissertationPanelLayout.setHorizontalGroup(
            AddDissertationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        AddDissertationPanelLayout.setVerticalGroup(
            AddDissertationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Dissertation", AddDissertationPanel);

        javax.swing.GroupLayout AddConferencePanelLayout = new javax.swing.GroupLayout(AddConferencePanel);
        AddConferencePanel.setLayout(AddConferencePanelLayout);
        AddConferencePanelLayout.setHorizontalGroup(
            AddConferencePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        AddConferencePanelLayout.setVerticalGroup(
            AddConferencePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Conference", AddConferencePanel);

        javax.swing.GroupLayout AddJournalPanelLayout = new javax.swing.GroupLayout(AddJournalPanel);
        AddJournalPanel.setLayout(AddJournalPanelLayout);
        AddJournalPanelLayout.setHorizontalGroup(
            AddJournalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        AddJournalPanelLayout.setVerticalGroup(
            AddJournalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Journal", AddJournalPanel);

        AddResearchTitleLable.setText("Title:");

        AddResearchPublisherLabel.setText("Publisher:");

        jButton3.setText("Add Research Paper");

        jLabel2.setText("Author List");

        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane3.setViewportView(jList1);

        javax.swing.GroupLayout AddResearchPalettePanel1Layout = new javax.swing.GroupLayout(AddResearchPalettePanel1);
        AddResearchPalettePanel1.setLayout(AddResearchPalettePanel1Layout);
        AddResearchPalettePanel1Layout.setHorizontalGroup(
            AddResearchPalettePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AddResearchPalettePanel1Layout.createSequentialGroup()
                .addGroup(AddResearchPalettePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(AddResearchTitleLable)
                    .addComponent(AddResearchPublisherLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(AddResearchPalettePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(AddResearchPalettePanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(68, 68, 68)
                        .addComponent(jButton3)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(AddResearchPalettePanel1Layout.createSequentialGroup()
                        .addGroup(AddResearchPalettePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(AddResearchPublisherTxt1, javax.swing.GroupLayout.DEFAULT_SIZE, 91, Short.MAX_VALUE)
                            .addComponent(AddResearchPaperAuthorLTxt)
                            .addComponent(AddMagazineTitleTxt1))
                        .addGap(0, 408, Short.MAX_VALUE))))
        );
        AddResearchPalettePanel1Layout.setVerticalGroup(
            AddResearchPalettePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AddResearchPalettePanel1Layout.createSequentialGroup()
                .addGroup(AddResearchPalettePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AddResearchTitleLable)
                    .addComponent(AddMagazineTitleTxt1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(AddResearchPalettePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AddResearchPublisherLabel)
                    .addComponent(AddResearchPublisherTxt1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(AddResearchPalettePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(AddResearchPalettePanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AddResearchPalettePanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                        .addComponent(AddResearchPaperAuthorLTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)))
                .addGroup(AddResearchPalettePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AddResearchPalettePanel1Layout.createSequentialGroup()
                        .addComponent(jButton3)
                        .addGap(48, 48, 48))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AddResearchPalettePanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18))))
        );

        javax.swing.GroupLayout AddResearchPanelLayout = new javax.swing.GroupLayout(AddResearchPanel);
        AddResearchPanel.setLayout(AddResearchPanelLayout);
        AddResearchPanelLayout.setHorizontalGroup(
            AddResearchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AddResearchPanelLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(AddResearchPalettePanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(40, Short.MAX_VALUE))
        );
        AddResearchPanelLayout.setVerticalGroup(
            AddResearchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AddResearchPanelLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(AddResearchPalettePanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(86, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Research", AddResearchPanel);

        AddMagazineTitleLable.setText("Title:");

        AddMagazinePublisherLabel.setText("Publisher:");

        jButton2.setText("Add Magazine");

        javax.swing.GroupLayout AddMagazinePalettePanelLayout = new javax.swing.GroupLayout(AddMagazinePalettePanel);
        AddMagazinePalettePanel.setLayout(AddMagazinePalettePanelLayout);
        AddMagazinePalettePanelLayout.setHorizontalGroup(
            AddMagazinePalettePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AddMagazinePalettePanelLayout.createSequentialGroup()
                .addGroup(AddMagazinePalettePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(AddMagazineTitleLable)
                    .addComponent(AddMagazinePublisherLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(AddMagazinePalettePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(AddMagazineTitleTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 91, Short.MAX_VALUE)
                    .addComponent(AddMagazinePublisherTxt))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(AddMagazinePalettePanelLayout.createSequentialGroup()
                .addGap(251, 251, 251)
                .addComponent(jButton2)
                .addContainerGap(251, Short.MAX_VALUE))
        );
        AddMagazinePalettePanelLayout.setVerticalGroup(
            AddMagazinePalettePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AddMagazinePalettePanelLayout.createSequentialGroup()
                .addGroup(AddMagazinePalettePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AddMagazineTitleLable)
                    .addComponent(AddMagazineTitleTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(AddMagazinePalettePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AddMagazinePublisherLabel)
                    .addComponent(AddMagazinePublisherTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 78, Short.MAX_VALUE)
                .addComponent(jButton2)
                .addGap(48, 48, 48))
        );

        javax.swing.GroupLayout AddMagazinePanelLayout = new javax.swing.GroupLayout(AddMagazinePanel);
        AddMagazinePanel.setLayout(AddMagazinePanelLayout);
        AddMagazinePanelLayout.setHorizontalGroup(
            AddMagazinePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AddMagazinePanelLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(AddMagazinePalettePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(12, Short.MAX_VALUE))
        );
        AddMagazinePanelLayout.setVerticalGroup(
            AddMagazinePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AddMagazinePanelLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(AddMagazinePalettePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(101, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Magazine", AddMagazinePanel);

        jLabel1.setText("Book Type");

        javax.swing.GroupLayout AddBookPaneLayout = new javax.swing.GroupLayout(AddBookPane);
        AddBookPane.setLayout(AddBookPaneLayout);
        AddBookPaneLayout.setHorizontalGroup(
            AddBookPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AddBookPaneLayout.createSequentialGroup()
                .addGroup(AddBookPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(AddBookPaneLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 638, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(AddBookPaneLayout.createSequentialGroup()
                        .addGap(239, 239, 239)
                        .addComponent(jLabel1)))
                .addContainerGap(84, Short.MAX_VALUE))
        );
        AddBookPaneLayout.setVerticalGroup(
            AddBookPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AddBookPaneLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 362, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(77, Short.MAX_VALUE))
        );

        MultiPaneLMS.addTab("Add Book", AddBookPane);

        BookJList.setModel(model);
        jScrollPane2.setViewportView(BookJList);

        RemoveBookButton.setText("Remove Book");
        RemoveBookButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RemoveBookButtonActionPerformed(evt);
            }
        });

        VerificationPanel.setVisible(false);
        VerificationPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        VerificationLabel.setText("Are you sure you wish to remove this book?");

        VerificationYesButton.setText("Yes");
        VerificationYesButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VerificationYesButtonActionPerformed(evt);
            }
        });

        VerificationNoButton.setText("No");
        VerificationNoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VerificationNoButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout VerificationPanelLayout = new javax.swing.GroupLayout(VerificationPanel);
        VerificationPanel.setLayout(VerificationPanelLayout);
        VerificationPanelLayout.setHorizontalGroup(
            VerificationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, VerificationPanelLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(VerificationYesButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 110, Short.MAX_VALUE)
                .addComponent(VerificationNoButton)
                .addGap(45, 45, 45))
            .addGroup(VerificationPanelLayout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(VerificationLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        VerificationPanelLayout.setVerticalGroup(
            VerificationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(VerificationPanelLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(VerificationLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(VerificationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(VerificationYesButton)
                    .addComponent(VerificationNoButton))
                .addContainerGap(30, Short.MAX_VALUE))
        );

        jButton1.setText("Edit Book");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        EdittingPane.setVisible(false);

        EditBookResearchPaper.setVisible(false);

        AddResearchTitleLable5.setText("Title:");

        AddResearchPublisherLabel5.setText("Publisher:");

        jButton4.setText("Add Research Paper");

        jLabel7.setText("Author List");

        jList6.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane8.setViewportView(jList6);

        javax.swing.GroupLayout EditBookResearchPaperLayout = new javax.swing.GroupLayout(EditBookResearchPaper);
        EditBookResearchPaper.setLayout(EditBookResearchPaperLayout);
        EditBookResearchPaperLayout.setHorizontalGroup(
            EditBookResearchPaperLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EditBookResearchPaperLayout.createSequentialGroup()
                .addGroup(EditBookResearchPaperLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(AddResearchTitleLable5)
                    .addComponent(AddResearchPublisherLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(EditBookResearchPaperLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(EditBookResearchPaperLayout.createSequentialGroup()
                        .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(68, 68, 68)
                        .addComponent(jButton4)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(EditBookResearchPaperLayout.createSequentialGroup()
                        .addGroup(EditBookResearchPaperLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(AddResearchPublisherTxt6, javax.swing.GroupLayout.DEFAULT_SIZE, 91, Short.MAX_VALUE)
                            .addComponent(AddResearchPaperAuthorLTxt5)
                            .addComponent(AddMagazineTitleTxt2))
                        .addGap(0, 289, Short.MAX_VALUE))))
        );
        EditBookResearchPaperLayout.setVerticalGroup(
            EditBookResearchPaperLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EditBookResearchPaperLayout.createSequentialGroup()
                .addGroup(EditBookResearchPaperLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AddResearchTitleLable5)
                    .addComponent(AddMagazineTitleTxt2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(EditBookResearchPaperLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AddResearchPublisherLabel5)
                    .addComponent(AddResearchPublisherTxt6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(EditBookResearchPaperLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(EditBookResearchPaperLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, EditBookResearchPaperLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(AddResearchPaperAuthorLTxt5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)))
                .addGroup(EditBookResearchPaperLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, EditBookResearchPaperLayout.createSequentialGroup()
                        .addComponent(jButton4)
                        .addGap(48, 48, 48))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, EditBookResearchPaperLayout.createSequentialGroup()
                        .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18))))
        );

        EdittingPane.addTab("Edit Research Paper", EditBookResearchPaper);

        EditBookMagazine.setVisible(false);

        AddMagazineTitleLable1.setText("Title:");

        AddMagazinePublisherLabel1.setText("Publisher:");

        jButton9.setText("Add Magazine");

        javax.swing.GroupLayout EditBookMagazineLayout = new javax.swing.GroupLayout(EditBookMagazine);
        EditBookMagazine.setLayout(EditBookMagazineLayout);
        EditBookMagazineLayout.setHorizontalGroup(
            EditBookMagazineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EditBookMagazineLayout.createSequentialGroup()
                .addGroup(EditBookMagazineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(AddMagazineTitleLable1)
                    .addComponent(AddMagazinePublisherLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(EditBookMagazineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(AddMagazineTitleTxt7, javax.swing.GroupLayout.DEFAULT_SIZE, 91, Short.MAX_VALUE)
                    .addComponent(AddMagazinePublisherTxt1))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(EditBookMagazineLayout.createSequentialGroup()
                .addGap(251, 251, 251)
                .addComponent(jButton9)
                .addContainerGap(104, Short.MAX_VALUE))
        );
        EditBookMagazineLayout.setVerticalGroup(
            EditBookMagazineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EditBookMagazineLayout.createSequentialGroup()
                .addGroup(EditBookMagazineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AddMagazineTitleLable1)
                    .addComponent(AddMagazineTitleTxt7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(EditBookMagazineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AddMagazinePublisherLabel1)
                    .addComponent(AddMagazinePublisherTxt1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                .addComponent(jButton9)
                .addGap(48, 48, 48))
        );

        EdittingPane.addTab("Edit Magazine", EditBookMagazine);

        javax.swing.GroupLayout RemoveBookPaneLayout = new javax.swing.GroupLayout(RemoveBookPane);
        RemoveBookPane.setLayout(RemoveBookPaneLayout);
        RemoveBookPaneLayout.setHorizontalGroup(
            RemoveBookPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RemoveBookPaneLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(RemoveBookPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(VerificationPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(RemoveBookPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jButton1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(RemoveBookButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(EdittingPane, javax.swing.GroupLayout.PREFERRED_SIZE, 461, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        RemoveBookPaneLayout.setVerticalGroup(
            RemoveBookPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RemoveBookPaneLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(RemoveBookPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 416, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(RemoveBookPaneLayout.createSequentialGroup()
                        .addComponent(RemoveBookButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1)
                        .addGap(18, 18, 18)
                        .addComponent(EdittingPane, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(VerificationPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(73, Short.MAX_VALUE))
        );

        MultiPaneLMS.addTab("Edit/Remove/Browse", RemoveBookPane);

        ReportTextArea.setColumns(20);
        ReportTextArea.setRows(5);
        jScrollPane1.setViewportView(ReportTextArea);

        GenReportButton.setText("Generate Complete Report");
        GenReportButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GenReportButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout GenerateReportPaneLayout = new javax.swing.GroupLayout(GenerateReportPane);
        GenerateReportPane.setLayout(GenerateReportPaneLayout);
        GenerateReportPaneLayout.setHorizontalGroup(
            GenerateReportPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(GenerateReportPaneLayout.createSequentialGroup()
                .addGroup(GenerateReportPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(GenerateReportPaneLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 646, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(GenerateReportPaneLayout.createSequentialGroup()
                        .addGap(211, 211, 211)
                        .addComponent(GenReportButton, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(76, Short.MAX_VALUE))
        );
        GenerateReportPaneLayout.setVerticalGroup(
            GenerateReportPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, GenerateReportPaneLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(GenReportButton, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 406, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        MultiPaneLMS.addTab("Generate Report", GenerateReportPane);

        javax.swing.GroupLayout RootPanelLayout = new javax.swing.GroupLayout(RootPanel);
        RootPanel.setLayout(RootPanelLayout);
        RootPanelLayout.setHorizontalGroup(
            RootPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MultiPaneLMS)
        );
        RootPanelLayout.setVerticalGroup(
            RootPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MultiPaneLMS)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 728, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(RootPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 530, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(RootPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void GenReportButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GenReportButtonActionPerformed
        /* NOTE <-- NOT IMPLEMENTED YET, NEED TO FINISH BOOK CLASSES
        String BookGenReportStr;
        for (int i; i<BookList.length; i++) {
            BookGenReportStr += BookList.toString();
        }
        ReportTextArea.setText(BookGenReportStr);
        */
    }//GEN-LAST:event_GenReportButtonActionPerformed

    private void VerificationNoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VerificationNoButtonActionPerformed
        VerificationPanel.setVisible(false);
    }//GEN-LAST:event_VerificationNoButtonActionPerformed

    private void VerificationYesButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VerificationYesButtonActionPerformed
        int index = BookJList.getSelectedIndex();
        System.out.println(index);
        if (index != -1) {
            BookStrList.remove(index); //This is perhaps redudant, the model below should be built by taking the first
            //BookList.remove(index); <- NOTE: Needs implementation
            model.removeElement(index);
            VerificationPanel.setVisible(false);
        }
    }//GEN-LAST:event_VerificationYesButtonActionPerformed

    private void RemoveBookButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RemoveBookButtonActionPerformed
        if (BookJList.getSelectedIndex() != -1) {
            VerificationPanel.setVisible(true);
        }
    }//GEN-LAST:event_RemoveBookButtonActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        EdittingPane.setVisible(true);
        EditBookResearchPaper.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LMS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LMS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LMS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LMS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LMS().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel AddBookPane;
    private javax.swing.JPanel AddBookPanel;
    private javax.swing.JPanel AddConferencePanel;
    private javax.swing.JPanel AddDissertationPanel;
    private javax.swing.JPanel AddJournalPanel;
    private javax.swing.JPanel AddMagazinePalettePanel;
    private javax.swing.JPanel AddMagazinePanel;
    private javax.swing.JLabel AddMagazinePublisherLabel;
    private javax.swing.JLabel AddMagazinePublisherLabel1;
    private javax.swing.JTextField AddMagazinePublisherTxt;
    private javax.swing.JTextField AddMagazinePublisherTxt1;
    private javax.swing.JLabel AddMagazineTitleLable;
    private javax.swing.JLabel AddMagazineTitleLable1;
    private javax.swing.JTextField AddMagazineTitleTxt;
    private javax.swing.JTextField AddMagazineTitleTxt1;
    private javax.swing.JTextField AddMagazineTitleTxt2;
    private javax.swing.JTextField AddMagazineTitleTxt3;
    private javax.swing.JTextField AddMagazineTitleTxt4;
    private javax.swing.JTextField AddMagazineTitleTxt5;
    private javax.swing.JTextField AddMagazineTitleTxt6;
    private javax.swing.JTextField AddMagazineTitleTxt7;
    private javax.swing.JPanel AddResearchPalettePanel1;
    private javax.swing.JPanel AddResearchPalettePanel2;
    private javax.swing.JPanel AddResearchPalettePanel3;
    private javax.swing.JPanel AddResearchPalettePanel4;
    private javax.swing.JPanel AddResearchPalettePanel5;
    private javax.swing.JPanel AddResearchPanel;
    private javax.swing.JTextField AddResearchPaperAuthorLTxt;
    private javax.swing.JTextField AddResearchPaperAuthorLTxt1;
    private javax.swing.JTextField AddResearchPaperAuthorLTxt2;
    private javax.swing.JTextField AddResearchPaperAuthorLTxt3;
    private javax.swing.JTextField AddResearchPaperAuthorLTxt4;
    private javax.swing.JTextField AddResearchPaperAuthorLTxt5;
    private javax.swing.JLabel AddResearchPublisherLabel;
    private javax.swing.JLabel AddResearchPublisherLabel1;
    private javax.swing.JLabel AddResearchPublisherLabel2;
    private javax.swing.JLabel AddResearchPublisherLabel3;
    private javax.swing.JLabel AddResearchPublisherLabel4;
    private javax.swing.JLabel AddResearchPublisherLabel5;
    private javax.swing.JTextField AddResearchPublisherTxt1;
    private javax.swing.JTextField AddResearchPublisherTxt2;
    private javax.swing.JTextField AddResearchPublisherTxt3;
    private javax.swing.JTextField AddResearchPublisherTxt4;
    private javax.swing.JTextField AddResearchPublisherTxt5;
    private javax.swing.JTextField AddResearchPublisherTxt6;
    private javax.swing.JLabel AddResearchTitleLable;
    private javax.swing.JLabel AddResearchTitleLable1;
    private javax.swing.JLabel AddResearchTitleLable2;
    private javax.swing.JLabel AddResearchTitleLable3;
    private javax.swing.JLabel AddResearchTitleLable4;
    private javax.swing.JLabel AddResearchTitleLable5;
    private javax.swing.JPanel AddThesisPanel;
    private javax.swing.JList<String> BookJList;
    private javax.swing.JPanel EditBookMagazine;
    private javax.swing.JPanel EditBookResearchPaper;
    private javax.swing.JTabbedPane EdittingPane;
    private javax.swing.JButton GenReportButton;
    private javax.swing.JPanel GenerateReportPane;
    private javax.swing.JTabbedPane MultiPaneLMS;
    private javax.swing.JButton RemoveBookButton;
    private javax.swing.JPanel RemoveBookPane;
    private javax.swing.JTextArea ReportTextArea;
    private javax.swing.JPanel RootPanel;
    private javax.swing.JLabel VerificationLabel;
    private javax.swing.JButton VerificationNoButton;
    private javax.swing.JPanel VerificationPanel;
    private javax.swing.JButton VerificationYesButton;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JList<String> jList1;
    private javax.swing.JList<String> jList2;
    private javax.swing.JList<String> jList3;
    private javax.swing.JList<String> jList4;
    private javax.swing.JList<String> jList5;
    private javax.swing.JList<String> jList6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JTabbedPane jTabbedPane1;
    // End of variables declaration//GEN-END:variables
}
