package PopUpFrames;
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author nohea
 */
public class BookFrame extends javax.swing.JFrame {

    /**
     * Creates new form EditRemoveForm
     */
    public BookFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BookRootPanel = new javax.swing.JPanel();
        editRemoveBookLabel = new javax.swing.JLabel();
        editRemoveBookPanel = new javax.swing.JPanel();
        eRBookTitleLabel = new javax.swing.JLabel();
        eRBookTitleTxt = new javax.swing.JTextField();
        eRBookPubYearLabel = new javax.swing.JLabel();
        eRBookPubYearTxt = new javax.swing.JTextField();
        eRBookEdNumLabel = new javax.swing.JLabel();
        eRBookEdNumTxt = new javax.swing.JTextField();
        eRBookChapLabel = new javax.swing.JLabel();
        eRBookChapTxt = new javax.swing.JTextField();
        eRBookFigLabel = new javax.swing.JLabel();
        eRBookFigTxt = new javax.swing.JTextField();
        eRBookPubLabel = new javax.swing.JLabel();
        eRBookPubTxt = new javax.swing.JTextField();
        eRBookAuthorInstrucLabel = new javax.swing.JLabel();
        eRBookAuhorLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        eRBookAuthorTxt = new javax.swing.JTextArea();
        editBookBtn = new javax.swing.JButton();
        removeBookBtn = new javax.swing.JButton();
        addBookBtn = new javax.swing.JButton();
        backBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(109, 95));

        BookRootPanel.setBackground(new java.awt.Color(60, 91, 118));

        editRemoveBookLabel.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 24)); // NOI18N
        editRemoveBookLabel.setForeground(new java.awt.Color(250, 250, 250));
        editRemoveBookLabel.setText("Add/Edit/Remove Book");

        eRBookTitleLabel.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 14)); // NOI18N
        eRBookTitleLabel.setText("Title:");

        eRBookTitleTxt.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 14)); // NOI18N
        eRBookTitleTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eRBookTitleTxtActionPerformed(evt);
            }
        });

        eRBookPubYearLabel.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 14)); // NOI18N
        eRBookPubYearLabel.setText("Publication Year:");

        eRBookPubYearTxt.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 14)); // NOI18N

        eRBookEdNumLabel.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 14)); // NOI18N
        eRBookEdNumLabel.setText("Edition Number:");

        eRBookEdNumTxt.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 14)); // NOI18N

        eRBookChapLabel.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 14)); // NOI18N
        eRBookChapLabel.setText("Chapters:");

        eRBookChapTxt.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 14)); // NOI18N

        eRBookFigLabel.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 14)); // NOI18N
        eRBookFigLabel.setText("Number of Figures:");

        eRBookFigTxt.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 14)); // NOI18N

        eRBookPubLabel.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 14)); // NOI18N
        eRBookPubLabel.setText("Publisher:");

        eRBookPubTxt.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 14)); // NOI18N

        eRBookAuthorInstrucLabel.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 14)); // NOI18N
        eRBookAuthorInstrucLabel.setText("Enter the author(s) of the book. If there are multiple, seprate them by a semicolon. (;)");

        eRBookAuhorLabel.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 14)); // NOI18N
        eRBookAuhorLabel.setText("Authors:");

        eRBookAuthorTxt.setColumns(20);
        eRBookAuthorTxt.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 14)); // NOI18N
        eRBookAuthorTxt.setRows(5);
        jScrollPane1.setViewportView(eRBookAuthorTxt);

        editBookBtn.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 18)); // NOI18N
        editBookBtn.setText("Edit Book");

        removeBookBtn.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 18)); // NOI18N
        removeBookBtn.setText("Remove Book");

        addBookBtn.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 18)); // NOI18N
        addBookBtn.setText("Add Book");

        javax.swing.GroupLayout editRemoveBookPanelLayout = new javax.swing.GroupLayout(editRemoveBookPanel);
        editRemoveBookPanel.setLayout(editRemoveBookPanelLayout);
        editRemoveBookPanelLayout.setHorizontalGroup(
            editRemoveBookPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(editRemoveBookPanelLayout.createSequentialGroup()
                .addGroup(editRemoveBookPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(editRemoveBookPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(editRemoveBookPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(eRBookEdNumLabel)
                            .addComponent(eRBookPubYearLabel)
                            .addComponent(eRBookTitleLabel)
                            .addComponent(eRBookChapLabel)
                            .addComponent(eRBookFigLabel))
                        .addGap(18, 18, 18)
                        .addGroup(editRemoveBookPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(eRBookTitleTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(eRBookPubYearTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(editRemoveBookPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(eRBookFigTxt, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 82, Short.MAX_VALUE)
                                .addComponent(eRBookChapTxt, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(eRBookEdNumTxt, javax.swing.GroupLayout.Alignment.LEADING))))
                    .addGroup(editRemoveBookPanelLayout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addGroup(editRemoveBookPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(editRemoveBookPanelLayout.createSequentialGroup()
                                .addComponent(eRBookPubLabel)
                                .addGap(18, 18, 18)
                                .addComponent(eRBookPubTxt))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, editRemoveBookPanelLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(editRemoveBookPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(eRBookAuthorInstrucLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, editRemoveBookPanelLayout.createSequentialGroup()
                                        .addComponent(eRBookAuhorLabel)
                                        .addGap(18, 18, 18)
                                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 432, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                .addGroup(editRemoveBookPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(editRemoveBookPanelLayout.createSequentialGroup()
                        .addGap(94, 94, 94)
                        .addComponent(removeBookBtn))
                    .addGroup(editRemoveBookPanelLayout.createSequentialGroup()
                        .addGap(111, 111, 111)
                        .addGroup(editRemoveBookPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(addBookBtn)
                            .addComponent(editBookBtn))))
                .addContainerGap(87, Short.MAX_VALUE))
        );
        editRemoveBookPanelLayout.setVerticalGroup(
            editRemoveBookPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(editRemoveBookPanelLayout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(editRemoveBookPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(eRBookTitleTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(eRBookTitleLabel))
                .addGap(18, 18, 18)
                .addGroup(editRemoveBookPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(eRBookPubYearLabel)
                    .addComponent(eRBookPubYearTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(editRemoveBookPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(eRBookEdNumLabel)
                    .addComponent(eRBookEdNumTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(editRemoveBookPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(eRBookChapLabel)
                    .addComponent(eRBookChapTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(editRemoveBookPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(eRBookFigLabel)
                    .addComponent(eRBookFigTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(editRemoveBookPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(eRBookPubLabel)
                    .addComponent(eRBookPubTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(addBookBtn)
                .addGap(7, 7, 7)
                .addGroup(editRemoveBookPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(editRemoveBookPanelLayout.createSequentialGroup()
                        .addComponent(eRBookAuthorInstrucLabel)
                        .addGap(34, 34, 34)
                        .addGroup(editRemoveBookPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(eRBookAuhorLabel)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(editRemoveBookPanelLayout.createSequentialGroup()
                        .addComponent(editBookBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(removeBookBtn)))
                .addContainerGap(32, Short.MAX_VALUE))
        );

        backBtn.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 18)); // NOI18N
        backBtn.setText("Back to Search");

        javax.swing.GroupLayout BookRootPanelLayout = new javax.swing.GroupLayout(BookRootPanel);
        BookRootPanel.setLayout(BookRootPanelLayout);
        BookRootPanelLayout.setHorizontalGroup(
            BookRootPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BookRootPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(editRemoveBookPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(BookRootPanelLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(editRemoveBookLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 308, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(backBtn)
                .addGap(73, 73, 73))
        );
        BookRootPanelLayout.setVerticalGroup(
            BookRootPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BookRootPanelLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(BookRootPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(editRemoveBookLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(backBtn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                .addComponent(editRemoveBookPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(BookRootPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(BookRootPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void eRBookTitleTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eRBookTitleTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_eRBookTitleTxtActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BookFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BookFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BookFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BookFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BookFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel BookRootPanel;
    private javax.swing.JButton addBookBtn;
    private javax.swing.JButton backBtn;
    private javax.swing.JLabel eRBookAuhorLabel;
    private javax.swing.JLabel eRBookAuthorInstrucLabel;
    private javax.swing.JTextArea eRBookAuthorTxt;
    private javax.swing.JLabel eRBookChapLabel;
    private javax.swing.JTextField eRBookChapTxt;
    private javax.swing.JLabel eRBookEdNumLabel;
    private javax.swing.JTextField eRBookEdNumTxt;
    private javax.swing.JLabel eRBookFigLabel;
    private javax.swing.JTextField eRBookFigTxt;
    private javax.swing.JLabel eRBookPubLabel;
    private javax.swing.JTextField eRBookPubTxt;
    private javax.swing.JLabel eRBookPubYearLabel;
    private javax.swing.JTextField eRBookPubYearTxt;
    private javax.swing.JLabel eRBookTitleLabel;
    private javax.swing.JTextField eRBookTitleTxt;
    private javax.swing.JButton editBookBtn;
    private javax.swing.JLabel editRemoveBookLabel;
    private javax.swing.JPanel editRemoveBookPanel;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton removeBookBtn;
    // End of variables declaration//GEN-END:variables
}
