package PopUpFrames;
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author nohea
 */
public class ResearchFrame extends javax.swing.JFrame {

    /**
     * Creates new form ResearchFrame
     */
    public ResearchFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ResearchRootPanel = new javax.swing.JPanel();
        editRemoveReserachLabel = new javax.swing.JLabel();
        editRemoveResearchPanel = new javax.swing.JPanel();
        eRResearchTitleLabel = new javax.swing.JLabel();
        erResearchTitleTxt = new javax.swing.JTextField();
        eRResearchPubYearLabel = new javax.swing.JLabel();
        eRResearchPubYearTxt = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        erResearchAuthorLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        eRResearchAuthorTxt = new javax.swing.JTextArea();
        removeResearchBtn = new javax.swing.JButton();
        editResearchBtn = new javax.swing.JButton();
        addResearchBtn = new javax.swing.JButton();
        backBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        ResearchRootPanel.setBackground(new java.awt.Color(60, 91, 118));

        editRemoveReserachLabel.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 24)); // NOI18N
        editRemoveReserachLabel.setForeground(new java.awt.Color(250, 250, 250));
        editRemoveReserachLabel.setText("Add/Edit/Remove Research Report");

        eRResearchTitleLabel.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 14)); // NOI18N
        eRResearchTitleLabel.setText("Title:");

        erResearchTitleTxt.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 14)); // NOI18N

        eRResearchPubYearLabel.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 14)); // NOI18N
        eRResearchPubYearLabel.setText("Publication Year:");

        eRResearchPubYearTxt.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 14)); // NOI18N

        jLabel1.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 14)); // NOI18N
        jLabel1.setText("Enter the author(s) of the journal. If there are multiple, seprate them by a semicolon. (;)");

        erResearchAuthorLabel.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 14)); // NOI18N
        erResearchAuthorLabel.setText("Authors:");

        eRResearchAuthorTxt.setColumns(20);
        eRResearchAuthorTxt.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 14)); // NOI18N
        eRResearchAuthorTxt.setRows(5);
        jScrollPane1.setViewportView(eRResearchAuthorTxt);

        removeResearchBtn.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 18)); // NOI18N
        removeResearchBtn.setText("Remove Research Report");

        editResearchBtn.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 18)); // NOI18N
        editResearchBtn.setText("Edit Research Report");

        addResearchBtn.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 18)); // NOI18N
        addResearchBtn.setText("Add Research Report");

        javax.swing.GroupLayout editRemoveResearchPanelLayout = new javax.swing.GroupLayout(editRemoveResearchPanel);
        editRemoveResearchPanel.setLayout(editRemoveResearchPanelLayout);
        editRemoveResearchPanelLayout.setHorizontalGroup(
            editRemoveResearchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(editRemoveResearchPanelLayout.createSequentialGroup()
                .addGroup(editRemoveResearchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(editRemoveResearchPanelLayout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addGroup(editRemoveResearchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(eRResearchPubYearLabel)
                            .addComponent(eRResearchTitleLabel))
                        .addGap(18, 18, 18)
                        .addGroup(editRemoveResearchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(erResearchTitleTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 459, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(eRResearchPubYearTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(editRemoveResearchPanelLayout.createSequentialGroup()
                        .addGap(73, 73, 73)
                        .addComponent(jLabel1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(editRemoveResearchPanelLayout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(erResearchAuthorLabel)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 451, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 78, Short.MAX_VALUE)
                .addGroup(editRemoveResearchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, editRemoveResearchPanelLayout.createSequentialGroup()
                        .addComponent(removeResearchBtn)
                        .addGap(54, 54, 54))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, editRemoveResearchPanelLayout.createSequentialGroup()
                        .addGroup(editRemoveResearchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(addResearchBtn)
                            .addComponent(editResearchBtn))
                        .addGap(69, 69, 69))))
        );
        editRemoveResearchPanelLayout.setVerticalGroup(
            editRemoveResearchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(editRemoveResearchPanelLayout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addGroup(editRemoveResearchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(editRemoveResearchPanelLayout.createSequentialGroup()
                        .addComponent(addResearchBtn)
                        .addGap(18, 18, 18)
                        .addComponent(editResearchBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(removeResearchBtn))
                    .addGroup(editRemoveResearchPanelLayout.createSequentialGroup()
                        .addGroup(editRemoveResearchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(eRResearchTitleLabel)
                            .addComponent(erResearchTitleTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(35, 35, 35)
                        .addGroup(editRemoveResearchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(eRResearchPubYearLabel)
                            .addComponent(eRResearchPubYearTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(58, 58, 58)
                        .addComponent(jLabel1)
                        .addGap(37, 37, 37)
                        .addGroup(editRemoveResearchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(erResearchAuthorLabel)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(67, Short.MAX_VALUE))
        );

        backBtn.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 18)); // NOI18N
        backBtn.setText("Back to Search");

        javax.swing.GroupLayout ResearchRootPanelLayout = new javax.swing.GroupLayout(ResearchRootPanel);
        ResearchRootPanel.setLayout(ResearchRootPanelLayout);
        ResearchRootPanelLayout.setHorizontalGroup(
            ResearchRootPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ResearchRootPanelLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(editRemoveReserachLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(backBtn)
                .addGap(59, 59, 59))
            .addGroup(ResearchRootPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(editRemoveResearchPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        ResearchRootPanelLayout.setVerticalGroup(
            ResearchRootPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ResearchRootPanelLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(ResearchRootPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(editRemoveReserachLabel)
                    .addComponent(backBtn))
                .addGap(44, 44, 44)
                .addComponent(editRemoveResearchPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ResearchRootPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ResearchRootPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ResearchFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ResearchFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ResearchFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ResearchFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ResearchFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel ResearchRootPanel;
    private javax.swing.JButton addResearchBtn;
    private javax.swing.JButton backBtn;
    private javax.swing.JTextArea eRResearchAuthorTxt;
    private javax.swing.JLabel eRResearchPubYearLabel;
    private javax.swing.JTextField eRResearchPubYearTxt;
    private javax.swing.JLabel eRResearchTitleLabel;
    private javax.swing.JPanel editRemoveResearchPanel;
    private javax.swing.JLabel editRemoveReserachLabel;
    private javax.swing.JButton editResearchBtn;
    private javax.swing.JLabel erResearchAuthorLabel;
    private javax.swing.JTextField erResearchTitleTxt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton removeResearchBtn;
    // End of variables declaration//GEN-END:variables
}
